import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Roboto } from 'next/font/google';
import './globals.css';


const poppins = Poppins({ 
  weight: ['400', '700'], 
  subsets: ['latin'],
  variable: '--poppins', 
});


const roboto = Roboto({ 
  weight: ['400', '500'], 
  subsets: ['latin'],
  variable: '--roboto', 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${poppins.variable} ${roboto.variable}`}>
      <body>
        {children}
        </body>
    </html>
  );
}
